# 注释版本
server:
  port: 18084
spring:
  application:
    name: api-gateway # 应用名
  cloud:
    gateway:
      routes:
        #id唯一标识，可自定义
        - id: user-service-route

          #路由的服务地址(非动态路由)
          uri: http://localhost:18081

#          #lb协议表示从Eureka注册中心获取服务请求地址
#          #user-provider访问的服务名称。
#          #路由地址如果通过lb协议加服务名称时，会自动使用负载均衡访问对应服务
#          uri: lb://user-provider
#
          # 路由断言：路由拦截规则
          predicates:
            #- Path=/user/**
            #注意：要想接下来的前缀过滤器生效，此处拦截规则为所有url:/**
            - Path=/**
          filters:
            #- PrefixPath=/user  # 给当前路由所有请求，添加"/user"前缀
            - StripPrefix=1  # 去除路径前缀过滤器，一个"/"识别为一个路径
            #配置自定义局部过滤器，此处的名字与过滤器声明时的前缀一致
            - MyParam=name


      #默认过滤器配置
      default-filters:
        # 往响应过滤器中加入响应头信息
        - AddResponseHeader=X-Response-Default-MyName,itheima


# Eureka服务中心配置
eureka:
  client:
    service-url:
      # 注册Eureka Server集群
      defaultZone: http://127.0.0.1:7001/eureka
